apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-api
  namespace: api-service
  labels:
    chaos: "true"
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args: ["--cpu", "2", "--timeout", "300s"]
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "2000m"
        memory: "128Mi"
  restartPolicy: Never

